--1)
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M1.INVOICE_NO, M2.LINE_NO, M2.ORDER_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
                      AND M2.ITEM_CD    IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE = '2023-01-04';

--2)
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD, SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
                      AND M2.ITEM_CD    IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-03' AND '2023-01-04'
 GROUP BY M1.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD;

--3)
SELECT INVOICE_NO, ORDER_NM
  FROM (
        SELECT M1.INVOICE_NO, M1.ORDER_NM, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1
               JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                              AND M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.BRAND_CD      = '1001'
           AND M1.OUTBOUND_DATE BETWEEN '2023-01-04' AND '2023-01-05'
         GROUP BY M1.INVOICE_NO, M1.ORDER_NM
         ORDER BY SUM_QTY DESC
       )
 WHERE ROWNUM = 1;
 


--1)
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M2.INVOICE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
                      AND M2.ORDER_QTY  >= 3
       JOIN A_ITEM C1  ON C1.BRAND_CD   = M2.BRAND_CD
                      AND C1.ITEM_CD    = M2.ITEM_CD
 WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04';

--2)
SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
       JOIN A_ITEM C1  ON C1.BRAND_CD   = M2.BRAND_CD
                      AND C1.ITEM_CD    = M2.ITEM_CD
 WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX;
 
--3)
SELECT BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX, SUM_QTY
      ,TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
      ,MOD  (SUM_QTY , QTY_IN_BOX) AS PCS_CNT
  FROM (
        SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1
               JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                              AND M2.INVOICE_NO = M1.INVOICE_NO
               JOIN A_ITEM C1  ON C1.BRAND_CD   = M2.BRAND_CD
                              AND C1.ITEM_CD    = M2.ITEM_CD
         WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
         GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
       );

--4)
SELECT *
  FROM (--2)
        SELECT BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX, SUM_QTY
              ,TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
              ,MOD  (SUM_QTY , QTY_IN_BOX) AS PCS_CNT
          FROM (--1)
                SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_M M1
                       JOIN A_OUT_D M2 ON M2.BRAND_CD   = M1.BRAND_CD
                                      AND M2.INVOICE_NO = M1.INVOICE_NO
                       JOIN A_ITEM C1  ON C1.BRAND_CD   = M2.BRAND_CD
                                      AND C1.ITEM_CD    = M2.ITEM_CD
                 WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
                 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
               )
         ORDER BY BOX_CNT DESC
       )
 WHERE ROWNUM <= 3;
 