SELECT NVL(NULL, 'EXISTS') VAL
    FROM DUAL
   WHERE 1= 1;
   
SELECT NVL(NULL, 'EXISTS') VAL
    FROM DUAL
   WHERE 1 = 2; 
   
SELECT NVL(MAX(NULL), 'HELLO') AS VAL
    FROM DUAL
   WHERE 1 = 2; 
   
SELECT 1 AS VAL 
    FROM DUAL
UNION ALL
SELECT 2 AS VAL 
    FROM DUAL
UNION ALL
SELECT NULL AS VAL 
    FROM DUAL
UNION ALL
SELECT 3 AS VAL 
    FROM DUAL;
    
SELECT SUM(NVL(VAL, 0)) 
      ,COUNT(*), COUNT(VAL), COUNT(1), COUNT(VAL), 
    FROM (--함수를 사용하면 NULL 이 사라진다.
         SELECT 1 AS VAL 
    FROM DUAL
UNION ALL
SELECT 2 AS VAL 
    FROM DUAL
UNION ALL
SELECT NULL AS VAL 
    FROM DUAL
UNION ALL
SELECT 3 AS VAL 
    FROM DUAL
         );
   
--DAY 8. 내장함수 일반 PAGE 18   
--1
SELECT BRAND_CD, COUNT(*)
    FROM A_OUT_M
   GROUP BY BRAND_CD;
   
--2
SELECT BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'DAY'), COUNT(*)
    FROM A_OUT_M
   GROUP BY BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'DAY');
   
--3
SELECT BRAND_CD, MOD_VAL, SUM(ORDER_QTY)
    FROM(
        SELECT BRAND_CD
               ,INVOICE_NO
               ,CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) 
                        WHEN 0 THEN '짝'
                        ELSE        '홀'
                END AS MOD_VAL
                ,ORDER_QTY
            FROM A_OUT_D
        )
  GROUP BY BRAND_CD, MOD_VAL;

--PAGE17
--2
SELECT OUTBOUND_DATE
       ,TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY       
       ,INVOICE_NO
       ,CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) 
            WHEN 0 THEN '짝'
            ELSE        '홀'
       END AS MOD_VAL
       ,ORDER_NM
    FROM A_OUT_M;
   
--PAGE 19
SELECT INVOICE_NO, OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY, OUTBOUND_NO
    FROM LO_OUT_M
   WHERE INVOICE_NO IN ('346724706214', '346724793596', '346724869970')
  ORDER BY OUTBOUND_DATE;
  
--PAGE20
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'EMPTY..') AS ORDER_QTY
    FROM LO_OUT_D
   WHERE INVOICE_NO = '346724706215';
    