SELECT M1.ITEM_CD, SUM(M1.ORDER_QTY) AS SUM_QTY
      ,(
       SELECT S1.ITEM_NM
        FROM CM_ITEM S1
       WHERE S1.ITEM_CD = M1.ITEM_CD 
       ) AS ITEM_NM
    FROM LO_OUT_D M1
   WHERE M1.INVOICE_NO BETWEEN '346724706262' AND '346724706762' 
  GROUP BY M1.ITEM_CD;
  
SELECT M1.ITEM_CD, SUM(M1.ORDER_QTY) AS SUM_QTY
      FROM LO_OUT_D M1
        JOIN CM_ITEM C1 ON C1.ITEM_CD = M1.ITEM_CD
   WHERE M1.INVOICE_NO BETWEEN '346724706262' AND '346724706762' 
  GROUP BY M1.ITEM_CD;   
  
SELECT ROWNUM AS RNK, ITEM_CD, QTY_IN_BOX, SUM_QTY
      ,TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
      ,MOD  (SUM_QTY , QTY_IN_BOX) AS PCS_CNT
      ,CEIL (SUM_QTY / QTY_IN_BOX) AS BOX_CNT_TOT
      FROM (
            SELECT ITEM_CD, QTY_IN_BOX, SUM(ORDER_QTY) AS SUM_QTY
                FROM LO_OUT_D          
              WHERE INVOICE_NO BETWEEN '346724706262' AND '346724706762'
            GROUP BY ITEM_CD, QTY_IN_BOX
            ORDER BY SUM_QTY DESC
            )
 WHERE ROWNUM <= 5;            
  
   